#we will pass the parsed data into the embeddings model
import time
import logfire
from langchain_google_genai import GoogleGenerativeAIEmbeddings

from app.config import settings # import the config keys

BATCH_SIZE = 50 #BATCH_SIZE determines how many chunks are sent to the embedding model in a single batch.
_GEMINI_DIM = 3072 #This represents the number of dimensions in each embedding vector generated by your Gemini model.
_FALLBACK_DIM = 768 #fallback model: all-mpnet-base-v2

#to select the active model
_active_model = None
_model_type: str | None = None

def probe_gemini():
    # ping the embed model once to check if it's reachable. Returns model or None
    try:
        model = GoogleGenerativeAIEmbeddings(
            model="models/gemini-embedding-2-preview",
            google_api_key=settings.GEMINI_API_KEY,
        )
        model.embed_query("probe")
        logfire.info("GEMINI embedding is ready")
        return model
    except Exception as e:
        logfire.warning(f"GEMINI embedding is not ready {e}. Will use the fallback embedding model")
        return None

def load_fallback_model():
    #loads fallback model
    from sentence_transformers import SentenceTransformer
    logfire.info("Loading sentence transformer fallback model. (all-mpnet-base-v2, 768-dim)")
    return SentenceTransformer("all-mpnet-base-v2")

def _init():
    global _active_model, _model_type

    if _active_model is not None:
        return

    model = probe_gemini()
    if model:
        _active_model = model
        _model_type = "gemini"
    else:
        _active_model = load_fallback_model()
        _model_type = "fallback"

def get_embedding_dim() -> int:
    #get the dims of the active model. Call after _init()
    _init()
    return _GEMINI_DIM if _model_type == "gemini" else _FALLBACK_DIM

def _embed_batch(batch: list[str]) -> list[list[float]]:
    #embed a batch of texts using the active model
    if _model_type == "gemini":
        # Exponential backoff: 1 s → 2 s → 4 s → 8 s (4 attempts total)
        for attempt in range(4):
            try:
                return _active_model.embed_documents(batch)
            except Exception as e:
                err = str(e).lower()
                is_rate_limit = any(x in err for x in ("429", "rate", "quota", "resource_exhausted"))
                if is_rate_limit and attempt < 3:
                    wait = 2 ** attempt
                    logfire.warning(
                        f"Gemini rate limit hit — retrying in {wait}s "
                        f"(attempt {attempt + 1}/4)."
                    )
                    time.sleep(wait)
                else:
                    logfire.error(f"Gemini embedding failed: {e}")
                    raise
        raise RuntimeError("Gemini rate limit persisted after 4 attempts.")
    else:
        return _active_model.encode(batch, show_progress_bar=False).tolist()

def embed_query(query: str) -> list[float]:
    _init()
    if _model_type == "gemini":
        return _active_model.embed_query(query)
    return _active_model.encode([query])[0].tolist()

def embed_texts(texts: list[str]) -> list[list[float]]:
    _init() #ping the active model and get its dims

    all_embeddings: list[list[float]] = []
    for i in range(0, len(texts), BATCH_SIZE): #select texts in batches
        batch = texts[i : min(i + BATCH_SIZE, len(texts))]
        with logfire.span("Embed batch", model = _model_type, start = i, size = len(batch)):
            all_embeddings.extend(_embed_batch(batch)) #store the current batch's embeddings

    return all_embeddings
